language: cpp
compiler: gcc
dist: trusty

os:
  - osx

before_script:

  - brew install ace
  - brew install mysql
  - brew install openssl
  - brew install tbb

  - mkdir build
  - cd build
  - cmake -DDEBUG=0 -DUSE_LIBCURL=1 ..

script: make -j4